package com.example.shopify.config;

import java.net.URI;
import org.springframework.core.env.Environment;

/** Intentionally not a record: an autogenerated toString must never print secrets. */
public final class ShopifySettings {
  private final String shop;
  private final String clientId;
  private final String clientSecret;
  private final String apiVersion;

  public ShopifySettings(String shop, String clientId, String clientSecret, String apiVersion) {
    if (shop == null || !shop.matches("[a-z0-9][a-z0-9-]*[a-z0-9]|[a-z0-9]")) {
      throw new IllegalArgumentException(
          "SHOPIFY_SHOP must be a myshopify subdomain without a URL or .myshopify.com.");
    }
    if (clientId == null || clientId.isBlank() || clientSecret == null || clientSecret.isBlank()) {
      throw new IllegalArgumentException(
          "Set SHOPIFY_CLIENT_ID and SHOPIFY_CLIENT_SECRET using JVM -D arguments.");
    }
    if (!"2026-07".equals(apiVersion)) {
      throw new IllegalArgumentException("This assessment requires SHOPIFY_API_VERSION=2026-07.");
    }
    this.shop = shop;
    this.clientId = clientId;
    this.clientSecret = clientSecret;
    this.apiVersion = apiVersion;
  }

  public static ShopifySettings from(Environment environment) {
    // JVM system properties take precedence over environment variables in Spring.
    return new ShopifySettings(
        environment.getProperty("SHOPIFY_SHOP"),
        environment.getProperty("SHOPIFY_CLIENT_ID"),
        environment.getProperty("SHOPIFY_CLIENT_SECRET"),
        environment.getProperty("SHOPIFY_API_VERSION", "2026-07"));
  }

  public URI baseUri() {
    return URI.create("https://" + shop + ".myshopify.com");
  }

  public String clientId() {
    return clientId;
  }

  public String clientSecret() {
    return clientSecret;
  }

  public String graphqlPath() {
    return "/admin/api/" + apiVersion + "/graphql.json";
  }
}
